### ISSUE TITLE
Adding tab navigation.

### ISSUE THREAD

**Issue by lukasoppermann** [EXSyst/recent-projects#10]
Another idea is to add tab navigation and open the projects on the user hitting return. That would be very awesome.

**Comment by xcv58** [comment]
+1
Use vim like navigation is better!

**Comment by Ener-Getick** [comment]
I do not have the time to develop that for the moment ...
If someone could, please make a PR: it could be a great feature !

**Comment by Ener-Getick** [comment]
I'm not sure to understand what you want ...
Can you provide me a schema or a picture please ?

**Comment by xcv58** [comment]
@Ener-Getick I'mean use `hjkl` to navigate in recent-projects view.
So we can open one project without mouse.

Actually, I prefer a fuzzy match method to select recent project, like Command Palette.
This is more efficient!

**Comment by Ener-Getick** [comment]
Ah ok I understand, I will try to do this tomorrow ☺
I thought you wanted one view per project...

**Comment by xcv58** [comment]
Cool! Thank you!

**Comment by xcv58** [comment]
It's great, thank you very much!

**Comment by Ener-Getick** [comment]
Thank you for this idea!

**Comment by lukasoppermann** [comment]
Awesome, are you planning to add up / down as well? Or is this to much work?

Technically if you could just calc how many items are in a row, you could easily get the index of the item.

Lets say, you have 3 per row, this means if I am on item 8 and go up, I need to go to 8-3 = 5. 

Cheers.

**Comment by Ener-Getick** [comment]
There are most of the time 3 tiles in a row but not always ...
I need to simulate the css properties. I will try to do this but it's a bit more complicated.

**Comment by lukasoppermann** [comment]
You could just calc it. Container size / item size.

**Comment by xcv58** [comment]
How about use add an `id` for all projects. Each time, you just need calc the index and directly select it.

**Comment by lukasoppermann** [comment]
I would not recommend this as it means when later on you add features like
favorites , etc. Which moves an item you have to recalc ids all the time.

**Comment by Ener-Getick** [comment]
I will think with a grid, it will be easier

**Comment by Ener-Getick** [comment]
Should I close this issue or do you have feedbacks ?

**Comment by lukasoppermann** [comment]
Works perfect for me. Thanks.
