### ISSUE TITLE
"Unexpected token u"

### ISSUE THREAD

**Issue by DavidLGoldberg** [EXSyst/recent-projects#11]
The following code returns the "Unexpected token u" on line 17:

```
read = (callback) ->
    fs.readFile getStateFilePath(), { encoding: 'utf8' }, if callback then (err, data) ->
        if err?
            if err.code == 'ENOENT'
                callback null, [ ]
            else
                callback err
        else
            data = JSON.parse(data) 
```

I got this by using the "audits" tab in chromium and setting to "Reload Page and Audit on Load"  Good luck!

p.s. Been using your package for a while, love it!

**Comment by Ener-Getick** [comment]
Is that still happening with the new commits ?
