### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by abdusfauzi** [EXSyst/recent-projects#14]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate (/Users/abdusfauzi/.atom/packages/recent-projects/lib/main.coffee:40:24)
```

**Comment by Moter8** [comment]
:+1:  Same issue here obviously.

**Comment by Ener-Getick** [comment]
Fixed by https://github.com/EXSyst/recent-projects/commit/b68d92dbf54ba8867f3d20292558b1596324981d.

Thank you.
