### ISSUE TITLE
Items cut off.

### ISSUE THREAD

**Issue by lukasoppermann** [EXSyst/recent-projects#15]
Hey, since the last update the projects are cut off at the top

![screen shot 2015-01-23 at 09 56 21](https://cloud.githubusercontent.com/assets/813754/5871998/251ff6c8-a2e6-11e4-96e4-06cc01f9e6d5.png)

**Comment by lukasoppermann** [comment]
Just letting you know it is still an issue.

**Comment by Ener-Getick** [comment]
Was atom in full screen when this bug happened ?

**Comment by lukasoppermann** [comment]
Nope, normal window mode on mac 10.10

On Wed, Jul 1, 2015, 5:37 PM Ener-Getick <notifications@github.com> wrote:

> Was atom in full screen when this bug happened ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EXSyst/recent-projects/issues/15#issuecomment-117718663>
> .
>
-- 
—
*veare*
Lukas Oppermann

M lukas@vea.re
W www.vea.re
P +49 163 162 69 47

**Comment by lukasoppermann** [comment]
Should this be in 0.4.3? Because after the update it still happens. It happens differently when the Inspector is open, if that is any help (e.g. more tiles are hidden.)

**Comment by Ener-Getick** [comment]
Fixed by 42142e5d9f95294e8e75ba0a62648dbe9ce85c37
