### ISSUE TITLE
Uneven sized elements due to flexbox.

### ISSUE THREAD

**Issue by lukasoppermann** [EXSyst/recent-projects#17]
Hey,

if one does not have an amount of items projects that works with the current number of items shown, you get something like in the screenshot.

### Fix
> **To "fix" this you just need to always append 2 empty project items (no styling, just empty lis) to the grid and it will always be fixed.**

![screen shot 2015-01-27 at 20 02 17](https://cloud.githubusercontent.com/assets/813754/5924858/6d3579a2-a65f-11e4-9706-3949c6ca1c5f.png)

**Comment by lukasoppermann** [comment]
This is still happening, fix described above.

**Comment by Ener-Getick** [comment]
I wait for feedbacks. I don't know if it's better to have a list in full screen or to have tiles with the same width.

**Comment by lukasoppermann** [comment]
What do you mean by this? It is still a problem, so it still happens. :(

**Comment by Ener-Getick** [comment]
It's not really a problem, it's the comportment provided by flexbox. 
So I don't know if I have to fix it...

**Comment by lukasoppermann** [comment]
Well, it is not technically a bug, but for a user, having the last item span 3 rows definitely is a design bug.
Why are you against fixing it? Its very easy, just drop 2 empty list items at the end. They have no height, so they do not interfere, but if they are needed, they fix this style bug. :)

**Comment by Ener-Getick** [comment]
Fixed by 9d31c5edf4260a31149839b686aaa12335962adf. Thank you.
