### ISSUE TITLE
The package doesn't seem to remember any recent projects

### ISSUE THREAD

**Issue by ignotus0001** [EXSyst/recent-projects#22]
Hey. Just downloaded and installed on Windows 7 ... I'm a new Atom user so I have the lastest-n-greatest of everything. I do get a recent project tab when I start Atom, and ctrl-shift-O will also bring up that tab. However, the thing is always empty; it doesn't seem to "remember" any recent folders/projects, etc. 

Am I doing something bone-headed? I checked settings; didnt seem to be anything there.

-BillyB

**Comment by andersea** [comment]
Allow me to be bone headed with you. I am wondering the same thing.

**Comment by tuxayo** [comment]
Might it have a link with #14 ?

**Comment by lukasoppermann** [comment]
Maybe somebody who knows how to fix this should clone the package and make a new one? It does not seem to be maintained. :(

**Comment by cfjedimaster** [comment]
Same here - this seems to be not working.

**Comment by oleynikd** [comment]
+1

**Comment by DiThi** [comment]
It stopped working at some point, not sure when because the old remembered projects kept appearing in the list. When I moved to a different PC, the list was empty and remained that way.

**Comment by Ener-Getick** [comment]
Fixed by https://github.com/EXSyst/recent-projects/commit/b68d92dbf54ba8867f3d20292558b1596324981d.
Thank you.
