### ISSUE TITLE
Uncaught SyntaxError: Unexpected number

### ISSUE THREAD

**Issue by averrin** [EXSyst/recent-projects#29]
[Enter steps to reproduce below:]

1. Just open Atom
2. Profit?

**Atom Version**: 1.0.0
**System**: Ubuntu 15.04
**Thrown From**: [recent-projects](https://github.com/EXSyst/recent-projects) package, v0.4.3

### Stack Trace

Uncaught SyntaxError: Unexpected number

```
At file:///usr/share/atom/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2Fhome%2Fuser%2Fprojects%2Fhealth-monitoring%22%7D%5D%2C%22bootstrapScript%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.0%22%2C%22shellLoadTime%22%3A4972%2C%22initialPaths%22%3A%5B%22%2Fhome%2Fuser%2Fprojects%2Fhealth-monitoring%22%5D%7D:1

SyntaxError: Unexpected number
  at Object.parse (native)
  at /home/user/.atom/packages/recent-projects/lib/recent-projects.js:24:25
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "accents-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "symbols-view",
      "web-browser",
      "deprecation-cop",
      "gulp-control",
      "tool-bar-main",
      "atom-ternjs",
      "Stylus",
      "atom-handlebars",
      "atom-jade",
      "hyperclick",
      "Hydrogen",
      "language-javascript-better",
      "minimap-pigments",
      "spell-check",
      "seti-icons",
      "js-refactor",
      "refactor",
      "atom-color-highlight",
      "flex-tool-bar",
      "local-history",
      "project-view",
      "tool-bar",
      "toolbar-basic",
      "background-tips",
      "image-view",
      "language-csharp",
      "linter-tidy"
    ]
  },
  "recent-projects": {
    "textOnly": true
  }
}
```

### Installed Packages

```coffee
# User
accents-ui, v0.3.0
atom-ctags, v4.1.4
atom-jinja2, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-python, v0.5.1
color-picker, v2.0.7
color-picker-service, v0.0.1
color-tabs, v0.1.3
css-snippets, v0.8.0
emmet, v2.3.12
file-icons, v1.5.8
foldername-tabs, v0.1.3
javascript-snippets, v1.0.0
language-jade, v0.4.0
linter, v1.1.0
linter-jshint, v0.1.7
linter-pep8, v0.2.0
linter-python-pyflakes, v0.1.0
minimap, v4.10.1
minimap-git-diff, v4.1.3
opened-files, v0.2.3
pigments, v0.8.2
project-manager, v1.15.10
recent-projects, v0.4.3
symbols-tree-view, v0.9.3
tree-view-git-status, v0.1.1
underline-trailing-whitespace, v1.0.1
up2date, v0.0.7

# Dev
No dev packages
```

**Comment by Ener-Getick** [comment]
Can you provide me your recent-project json file please ?
It is located in the atom folder : recent-project.json.Can you provide me your recent-project json file please ?
It is located in the atom folder : recent-project.json.

**Comment by averrin** [comment]
[{"devMode":true,"uri":"/home/user/.atom/packages/color-tabs","lastOpened":1435837042196},{"devMode":false,"uri":"/home/user/projects/health-monitoring","lastOpened":1435836025098},{"devMode":false,"uri":"/home/user/projects/book","lastOpened":1435832088470},{"devMode":false,"uri":"/home/user/projects/manage","lastOpened":1435832119550}]88470},{"devMode":false,"uri":"/home/user/projects/manage","lastOpened":1435832119550}]

>> {"devMode":false,"uri":"/home/user/projects/manage","lastOpened":1435832119550}]88470},
??? i didnt edit this file

**Comment by Ener-Getick** [comment]
To fix this bug temporarily, you must edit this file.
I'm searching for a solution.

**Comment by Ener-Getick** [comment]
I'm not sure that this bug could be resolved.
The problem is that the file write operation is asynchronous so if two operations happened on the same time, there is this bug ...

So the only solution for the moment is to don't go faster than the machine ...

**Comment by Ener-Getick** [comment]
Does the last version fix this error ?
