### ISSUE TITLE
minimap

### ISSUE THREAD

**Issue by mark-hahn** [EXSyst/recent-projects#3]
When I bring up recent-projects with ctrl-shift-O part of the pane is covered with a mini-map.

A minor bitch.  Can you shrink the icons a lot.  My screen isn't very big.  As far as I'm concerned a simple text-only list would be the best.  Are the icons ever different from the one I see?  If not then they add nothing.

Great package.

**Comment by Ener-Getick** [comment]
Is there someone who could give me a screenshot of this bug ?
