### ISSUE TITLE
Parse error on startup

### ISSUE THREAD

**Issue by blcarson** [EXSyst/recent-projects#33]
Getting this error when I first open Atom:

`Error parsing recent projects file: /Users/<username>/.atom/storage/recent-projects.json`

Here's the output of that file:

`[{"paths":["/Users/<username>/Sites/<project>"],"devMode":false,"lastOpened":1437682460703}]2460703}]`

**Comment by Ener-Getick** [comment]
Did you open two windows on the same time?
