### ISSUE TITLE
Buttom New File dont open new file editor on first try

### ISSUE THREAD

**Issue by DamianKuczaj** [EXSyst/recent-projects#36]
![screenshot_1](https://cloud.githubusercontent.com/assets/3974704/10018242/79e2e932-6135-11e5-9c00-9ef1857a5757.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/3974704/10018243/79f84048-6135-11e5-9899-4e0471726b52.png)

**Comment by Ener-Getick** [comment]
Even with the last version ?

**Comment by Ener-Getick** [comment]
ping

**Comment by DamianKuczaj** [comment]
Sory, this must be not problem from u plugin.
