### ISSUE TITLE
open recent project in same window

### ISSUE THREAD

**Issue by xnat9** [EXSyst/recent-projects#41]
can open recent project in same window? the function like command "add project folder"

**Comment by Ener-Getick** [comment]
It is probably possible but needs to be implemented... Can you create a PR please?

**Comment by xnat9** [comment]
i first in atom plugin,  i use atom.project.addPath instead of atom.open in my local. openProject function

**Comment by Ener-Getick** [comment]
Fixed in https://github.com/EXSyst/recent-projects/pull/47
