### ISSUE TITLE
Doesn't open a project window unless there's another tab open next to "Recent projects"

### ISSUE THREAD

**Issue by guncha** [EXSyst/recent-projects#44]
I really want to use this, but I'm running into this issue off the bat. I don't know how to debug Atom plugins, but here's what I found out.

If I start Atom from Spotlight (this is all on OS X), a new window is opened with the "Recent projects" tab. When I click on any of the projects, the window closes and no project is opened. The interesting part is that opening projects works fine if I open a new file tab next to the "Recent Projects" OR I already have a project open, in which case the same window is reused to open the project.

If I had to warrant a guess, it seems that `recent-project` is closing its tab before the project has opened and if the plugin is the only thing open, the window is closed with it.

I'm using Atom 1.7.4 with recent-projects 0.11.2. Let me know if you want more detailed info.

Edit: It works as it's supposed to if the *Open in New Window* option is selected.

**Comment by jeffm13** [comment]
+1.  I'm having the same issue.

**Comment by Ener-Getick** [comment]
Thanks for your report !
I'll try to fix it if i find some time ☺

**Comment by vnt** [comment]
+1. I'm having the same issue.
Mac os 10.11.5, Atom 1.8 Beta + recent-projects 0.11.2

**Comment by julienmoinard** [comment]
same issue

**Comment by cb1kenobi** [comment]
I'm also running into this issue with Atom 1.9.8 (OS X).

This is a super annoying bug, but now that I know I have to have a tab open (such as the preferences), I can at least find some usefulness from this plugin.

Things used to work perfectly, but something changed, probably with Atom, that prevents this from working correctly.

Toggling pending panes, close empty windows, and remove empty panes settings appear to have no effect.

**Comment by Ener-Getick** [comment]
I don't have the time to look at it for now but I would be glad to merge a PR is someone submits one :)

**Comment by Ener-Getick** [comment]
Fixed in https://github.com/EXSyst/recent-projects/pull/47
